version: 2.1

jobs:
  say-hello:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "this is the build job"
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Build and run checks
          command: ./gradlew build
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
